	tilepal 0, GRAY, BROWN, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, ROOF, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, BROWN, BROWN, GRAY
	tilepal 0, WATER, WATER, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, BROWN, GREEN, GREEN, GREEN
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, RED, RED, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
